server:
  port: 10010
spring:
  application:
    name: mall-product
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    sentinel:
      transport:
        dashboard: sentinel:8090
        port: 20010
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-i47fu02a.sql.tencentcdb.com:25704/spring_cloud_demo_mall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    password: mall@123
    username: mall
mybatis-plus:
  mapper-locations: /mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
feign:
  sentinel:
    enabled: true
