server:
  port: 10020
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-i47fu02a.sql.tencentcdb.com:25704/spring_cloud_demo_mall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    password: mall@123
    username: mall
mybatis-plus:
  mapper-locations: /mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

